import TED from '@/components/ted/TED';
import BaseLayout from '@/layouts/BaseLayout';
import Head from 'next/head';

export default function About() {
  return (
    <>
      <Head>
        <title>{'TED & Burslar | aidiyet.org'}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <BaseLayout>
        <TED />
      </BaseLayout>
    </>
  );
}
